Tests config for serialization of arrays
Karm/mandrel-integration-tests pull request #279
Opened 2024-09-09 15:25 UTC by Karm

* Depends on https://github.com/oracle/graal/issues/8509 being released via https://github.com/graalvm/graalvm-community-jdk21u/pull/10

* Depends on https://github.com/oracle/graal/issues/9581 being fixed, backported and released.

Merging it now would trigger failures for CI.

2024-09-09 16:07 UTC, Karm commented
```
 > but was: <Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: [Z (targetConstructorClass: java.lang.Object). Usually adding [Z to serialization-config.json fixes the problem.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:164)
	at java.base@22.0.2/jdk.internal.reflect.SerializationConstructorAccessorGenerator.generateSerializationConstructor(SerializationConstructorAccessorGenerator.java:51)
	at java.base@22.0.2/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:384)
	at java.base@22.0.2/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:288)
	at jdk.unsupported@22.0.2/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:100)
	at for_serialization.Main.main(Main.java:147)
	at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
>
[INFO] 
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0
```

Expected. The fix is not in the released JDK 22 Mandrel

2024-09-10 11:34 UTC, zakkak requested changes
> Expected. The fix is not in the released JDK 22 Mandrel

And it's not going to get backported to it, so we probably need to disable it in that configuration.

2024-09-10 11:34 UTC, zakkak commented on testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
> +    @IfMandrelVersion(minJDK = "23.1.5")
This should be:

```suggestion
    @IfMandrelVersion(min = "23.1.5")
```

no?

2024-09-13 08:48 UTC, Karm commented
> > Expected. The fix is not in the released JDK 22 Mandrel
> 
> And it's not going to get backported to it, so we probably need to disable it in that configuration.

I see, indeed. Lemme update it...

2024-09-16 15:33 UTC, zakkak commented
> or it's parsing Mandrel 24 as JDK 24?

The logs say
```
The test suite runs with Mandrel version 24.0.2 in container, JDK 22.0.2.
```

so it doesn't look like a parsing issue. 

I think the issue is that you are passing "21.999" as the `maxJDK` which doesn't match the pattern in https://github.com/Karm/mandrel-integration-tests/blob/9f6c895eb2de6a0b8dae8e50d826f31ee2b70606/testsuite/src/it/java/org/graalvm/tests/integration/utils/versions/MandrelVersionCondition.java#L46

2024-09-17 17:45 UTC, zakkak commented
@Karm thanks for the fix. I opened https://github.com/Karm/mandrel-integration-tests/issues/280 to keep track of the version parsing issue.

2024-09-17 17:45 UTC, zakkak approved these changes

2024-09-17 17:45 UTC, merged