Tests graalvm-community-jdk21u-issues-28
Karm/mandrel-integration-tests pull request #306
Opened 2024-12-17 23:52 UTC by Karm

Embeds the reproducer @zakkak outlined on the original issue.

Fails with current Mandrel for JDK 21, passes with e.g. Mandrel for JDK 23.

```
 mvn clean verify -Dquarkus.version=3.15.1 -Ptestsuite -Dtest=AppReproducersTest#jdkReflectionsTest
```

or in a container:

```
mvn clean verify -Ptestsuite-builder-image 
    -Dtest=AppReproducersTest#jdkReflectionsContainerTest -Dquarkus.version=3.15.1
    -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-23
    -Dquarkus.native.container-runtime=podman
    -Drootless.container-runtime=true -Dpodman.with.sudo=false | tee log.log
```
...swap jdk-23 with jdk-21 to see the fail.

2024-12-18 09:48 UTC, Karm commented
Hmm, it worries me that all tests in CI  passes. JDK 21 should have failed. Lemme take a look...

2024-12-18 10:22 UTC, zakkak commented
> Hmm, it worries me that all tests in CI passes. JDK 21 should have failed. Lemme take a look...

You set `minJDK = "21.0.3"` but the CI uses 

* Mandrel-23.1.1.0-Final which is Java version: 21.0.1+12-LTS
* Mandrel-23.1.2.0-Final which is Java version: 21.0.2+13-LTS
* Mandrel-24.0.1.0-Final which is Java version: 22.0.1+8 (which includes the fix)

2024-12-18 10:24 UTC, zakkak approved these changes
LGTM, other than the `minJDK` version being `21.0.3` while the test is expected to fail with any JDK 21 build.

2024-12-18 10:25 UTC, zakkak requested changes

2024-12-18 10:25 UTC, zakkak commented on testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
> +    @IfMandrelVersion(minJDK = "21.0.3", inContainer = true)
```suggestion
    @IfMandrelVersion(minJDK = "21.0.0", inContainer = true)
```

2024-12-18 10:25 UTC, zakkak commented on testsuite/src/it/java/org/graalvm/tests/integration/AppReproducersTest.java
> +    @IfMandrelVersion(minJDK = "21.0.3")
```suggestion
    @IfMandrelVersion(minJDK = "21.0.0")
```

2024-12-18 10:35 UTC, jerboaa approved these changes
OK (with the suggestions from @zakkak)

2024-12-18 10:35 UTC, jerboaa commented on testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java
> +            };
```suggestion
            return new Pattern[] {};
```

2024-12-19 09:48 UTC, zakkak approved these changes

2024-12-19 09:48 UTC, merged